quotes_to_scrape/quotes/urls.py
from django.urls import path

from . import views


app_name = "quotes"

urlpatterns = [
    path('', views.main, name='home'),
    path('parser/', views.parser, name='parser'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<int:_id>/', views.author_about, name='author_about'),
    path('accounts/profile/', views.main, name='home_auth'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('tag/<int:_id>/', views.find_by_tag, name='find_by_tag'),
    path('tag/<str:_id>/', views.find_by_tag, name='find_by_tag'),
    path('search/', views.search_form, name='search'),
]

quotes_to_scrape/quotes_to_scrape/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
    path('author/', include('quotes.urls')),
]

quotes_to_scrape/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.views import LoginView, LogoutView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name="users/login.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    # path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    #      name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_to_scrape/quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

quotes_to_scrape/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, ModelChoiceField, Select, \
    SelectMultiple
from .models import Quote, Author, Tag


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, required=True, widget=TextInput())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by("name"), required=True,
                                    widget=SelectMultiple())
    author = ModelChoiceField(queryset=Author.objects.all().order_by("fullname"), widget=Select())

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, widget=TextInput())
    born_date = CharField(max_length=50, widget=TextInput())
    born_location = CharField(max_length=150, widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class TagForm(ModelForm):
    name = CharField(max_length=50, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]

quotes_to_scrape/quotes/views.py
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import render, redirect
from django.http import HttpResponse,JsonResponse

from .models import Author, Quote, Tag
from .forms import QuoteForm, AuthorForm, TagForm
from .utils.scraper import start_parse


def main(request):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    top_ten_tags = Quote.objects.values('tags__name').annotate(quote_count=Count('id')).order_by('-quote_count')[:10]

    return render(request, "quotes/index.html", context={'quotes': page_obj, "top_ten_tags": top_ten_tags})


def author_about(request, _id):
    author = Author.objects.get(pk=_id)
    return render(request, 'quotes/author.html', context={'author': author})


def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:home")
        else:
            return render(request, "quotes/add_quote.html", context={'form': QuoteForm(), "message": "Form not valid"})
    return render(request, "quotes/add_quote.html", context={'form': QuoteForm()})


def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:home")
        else:
            return render(request, "quotes/add_author.html",
                          context={'form': AuthorForm(), "message": "Form not valid"})
    return render(request, "quotes/add_author.html", context={'form': AuthorForm()})


def add_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:home")
        else:
            return render(request, "quotes/add_tag.html", context={'form': TagForm(), "message": "Form not valid"})
    return render(request, "quotes/add_tag.html", context={'form': TagForm()})


def find_by_tag(request, _id):
    per_page = 5
    if isinstance(_id, int):
        quotes = Quote.objects.filter(tags=_id).all()
    elif isinstance(_id, str):
        _id = Tag.objects.filter(name=_id).first()
        quotes = Quote.objects.filter(tags=_id.id).all()

    top_ten_tags = Quote.objects.values('tags__name').annotate(quote_count=Count('id')).order_by('-quote_count')[:10]

    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "quotes/index.html", context={'quotes': page_obj, "top_ten_tags": top_ten_tags})


def search_form(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        if query:
            quotes = Quote.objects.filter(
                Q(quote__contains=query)
            )
            return render(request, "quotes/searchbar.html", context={'quotes': quotes, 'query': query})
        else:
            return render(request, "quotes/searchbar.html", {})


def parser(request):
    quotes = start_parse()
    return HttpResponse(render(request, "quotes/parser.html", context={"json_quotes": quotes}))

quotes_to_scrape/quotes/templates/quotes/add_author.html
{% extends "quotes/base1.html" %}

{% block content %}
<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label">Fullname
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label">Born Date
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label">Born Location
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label">Description
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

quotes_to_scrape/quotes/templates/quotes/add_quote.html
{% extends "quotes/base1.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label">Author
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label">Quote
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label " >Tags
            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>

    <div class="form-group row">
    <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
    </div>
</form>
{% endblock %}

quotes_to_scrape/quotes/templates/quotes/add_tag.html
{% extends "quotes/base1.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_tag' %}">
    {% csrf_token %}
    <div class="form-group row">
        <label for="floatingTextarea" class="col-sm-2 col-form-label">Tags
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

quotes_to_scrape/quotes/templates/quotes/author.html
{% extends "quotes/base1.html" %}
{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p>
        <strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span>
        <span class="author-born-location">{{author.born_location}}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>
{% endblock %}

quotes_to_scrape/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="/static/quotes/img/favicon-16x16.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>People Quotes</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-7">
            <h1>
                <a href="/" style="text-decoration: none">Quotes of famous people</a>
            </h1>
        </div>
        <div class="col-md-5">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-info">Add Quote</a>
                <a href="{% url 'quotes:add_author' %}" class="btn btn-info">Add Author</a>
                <a href="{% url 'quotes:add_tag' %}" class="btn btn-info">Add Tag</a>
                <a href="/users/logout" class="btn btn-light">Logout</a>
                <a href="{% url 'quotes:parser' %}" class="btn btn-warning">Parser</a>
                {% else %}
                <a href="/users/signup" class="btn btn-light">Signup</a>
                <a href="/users/signin" class="btn btn-light">Login</a>
                {% endif %}
            </p>
        </div>
    </div>
    <div class="col-md-5 pt-3 mb-3">
        <form action="{% url 'quotes:search' %}" method="get" class="d-flex">
          <input class="form-control me-2" type="text" name="query" placeholder="Search by quote" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>

    {% block content %} {% endblock %}

</div>
<footer>
  <div class="container">
    <h3>Leave a quote to stay in history</h3>
      <p>&copy; Made by <a href="https://github.com/AndriiSeeker/People-Quotes">Andrii Svitelskyi</a></p>
  </div>
</footer>
</body>
</html>

quotes_to_scrape/quotes/templates/quotes/base1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="/static/quotes/img/favicon-16x16.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>People Quotes</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-7">
            <h1>
                <a href="/" style="text-decoration: none">Quotes of famous people</a>
            </h1>
        </div>
        <div class="col-md-5">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-info">Add Quote</a>
                <a href="{% url 'quotes:add_author' %}" class="btn btn-info">Add Author</a>
                <a href="{% url 'quotes:add_tag' %}" class="btn btn-info">Add Tag</a>
                <a href="/users/logout" class="btn btn-light">Logout</a>
                <a href="{% url 'quotes:parser' %}" class="btn btn-warning">Parser</a>
                {% else %}
                <a href="/users/signup" class="btn btn-light">Signup</a>
                <a href="/users/signin" class="btn btn-light">Login</a>
                {% endif %}
            </p>
        </div>
    </div>

    {% block content %} {% endblock %}

</div>
</body>
</html>

quotes_to_scrape/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="row mb-3">
    <div class="col-md-8 themed-gris-col">
        {% if quotes %}
        {% for quote in quotes %}
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">{{quote.quote}}</span>
                <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                        <a class="tag" href="{% url 'quotes:find_by_tag' tag.id %}">{{tag}}</a>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        {% else %}
            <p>NO</p>
        {% endif %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    {% if quotes.has_previous %}
                    <a href="?page=1" class="btn btn-light">&laquo; first</a>
                    <a href="?page={{ quotes.previous_page_number }}" class="btn btn-light">previous</a>
                    {% endif %}
                    <span class="current">Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}</span>
                    {% if quotes.has_next %}
                    <a href="?page={{ quotes.next_page_number }}" class="btn btn-light">next</a>
                    <a href="?page={{ quotes.paginator.num_pages }}" class="btn btn-light">last &raquo;</a>
                    {% endif %}
            </ul>
        </nav>
    </div>
    <div class="col-md-4 themed-grid-col">
        <h2>Top 10 Tags</h2>
        {% for tag in top_ten_tags %}
        <div class="tags">
            <a class="tag" href="{% url 'quotes:find_by_tag' tag.tags__name %}">{{tag.tags__name}}</a>
        </div>
        {% endfor %}

    </div>

</div>


{% endblock %}

quotes_to_scrape/quotes/templates/quotes/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Quotes to Scrape</title>
</head>
<body>
    <div class="container">
        <div class="row pt-3 mb-3">
          <div class="col-md-5">
            <h1>
                <a href="/" style="text-decoration: none">Quotes of famous people</a>
            </h1>
          </div>
            <div class="col-md-6">
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-info">Add Quote</a>
                <a href="{% url 'quotes:add_author' %}" class="btn btn-info">Add Author</a>
                <a href="{% url 'quotes:add_tag' %}" class="btn btn-info">Add Tag</a>
                <a href="/users/logout" class="btn btn-light">Logout</a>
                <a href="{% url 'quotes:parser' %}" class="btn btn-warning">Parser</a>
                {% else %}
                <a href="/users/signup" class="btn btn-light">Signup</a>
                <a href="/users/signin" class="btn btn-light">Login</a>
                {% endif %}
            </div>
        </div>

    {% block content %} {% endblock %}
</div>

</body>
</html>

quotes_to_scrape/quotes/templates/quotes/parser.html
{% extends "quotes/base1.html" %}

{% block content %}
    {% for quote in json_quotes %}
        <span class="text" itemprop="text">{{quote}}</span>
        <p></p>
    {% endfor %}
{% endblock %}

quotes_to_scrape/quotes/templates/quotes/searchbar.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h2>Search results of "{{query}}"</h2>
    <div class="row mb-3">
    <div class="col-md-8 themed-gris-col">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                    <a class="tag" href="{% url 'quotes:find_by_tag' tag.id %}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

{% endblock %}