quotes_to_scrape/quotes_to_scrape/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
    path('author/', include('quotes.urls')),
]

quotes_to_scrape/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.views import LoginView, LogoutView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name="users/login.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    # path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    #      name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_to_scrape/users/models.py
from django.db import models

# Create your models here.

quotes_to_scrape/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    email = forms.CharField(max_length=100, required=True, widget=forms.EmailInput({'class': 'form-control'}))
    password1 = forms.CharField(max_length=50, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))
    password2 = forms.CharField(max_length=50, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    password = forms.CharField(max_length=50, min_length=5, required=True,
                               widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "password"]

quotes_to_scrape/users/views.py
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View

from .forms import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(to="quotes:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        if request.user.is_authenticated:
            return redirect(to='quotes:home')

        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаємо {username}. Ваш акаунт успішно створено!")
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:login')
    # success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

quotes_to_scrape/users/templates/users/login.html
{% extends 'quotes/base1.html' %}

{% block content %}

<h2>Login</h2>

{% if form.errors %}
    <ul class='form-errors'>
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% if messages %}
<div>
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" style="width: 60%;">
    {% csrf_token %}

    <div class="row mb-4">
        <label>Username:</label>
        {{form.username}}
        <span>{{form.errors.username}}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{form.password}}
        <span>{{form.errors.password}}</span>
    </div>
    <div class="d-grid gap-2 col-2 mx-auto">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
    </div>
    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

quotes_to_scrape/users/templates/users/logout.html
{% extends 'quotes/base1.html' %}

{% block content %}

<h1>Good bye</h1>

{% endblock %}

quotes_to_scrape/users/templates/users/password_reset.html
{% extends "quotes/base1.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-sm">Request password reset</button>
</form>

{% endblock %}

quotes_to_scrape/users/templates/users/password_reset_complete.html
{% extends "quotes/base1.html" %}

{% block content %}

  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="/users/signin" class="btn btn-primary">Login</a>
    </div>

{% endblock %}

quotes_to_scrape/users/templates/users/password_reset_confirm.html
{% extends "quotes/base1.html" %}

{% block title %}Enter new password{% endblock %}

{% block content %}

{% if validlink %}
<style>
input[type=button], input[type=submit], input[type=reset] {
  background-color: blue;
  border: none;
  color: white;
  padding: 8px 16px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 4px;
}
</style>

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Change my password">
</form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}
{% endblock %}

quotes_to_scrape/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account on the Quotes to Scrape. Please follow the link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, just ignore this email.</p>
<p>Thanks!</p>
{% endautoescape %}

quotes_to_scrape/users/templates/users/signup.html
{% extends 'quotes/base1.html' %}

{% block content %}

<h2>SignUp</h2>



<form method="post" style="width: 60%;">
    {% csrf_token %}

    <div class="row mb-4">
        <label>Username:</label>
        {{ form.username }}
        <span>{{ form.errors.username }}</span>
    </div>
    <div class="row mb-3">
        <label>Email:</label>
        {{ form.email }}
        <span>{{ form.errors.email }}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{ form.password1 }}
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{ form.password2}}
        <span>{{ form.errors.password2 }}</span>
    </div>

    <div class="d-grid gap-2 col-2 mx-auto">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
    </div>
</form>

{% endblock %}